#!/bin/bash --login
#SBATCH -J AmyHouseman_BWAindex
#SBATCH -o %x.stdout.%J.%N
#SBATCH -e %x.stderr.%J.%N
#SBATCH --ntasks=1
#SBATCH --ntasks-per-node=1
#SBATCH -p c_compute_wgp
#SBATCH --account=scw1581
#SBATCH --mail-type=ALL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=HousemanA@cardiff.ac.uk     # Where to send mail

cd /scratch/c.c20182028/bwa

#Load the singularity container for BWA
wget https://wotan.cardiff.ac.uk/containers/bwa-0.7.17.sif
module load singularity

#Run BWA using the index function and the HumanRefSeq file
singularity run bwa-0.7.17.sif index HumanRefSeq/GRCh38_latest_genomic.fna > IndexedHuman_output/
